<?php

namespace Contextr\Checks;

class Ai extends Check
{
    public string $subject = 'ai';

    public string $baseInstruction = 'Determine if this text was likely generated by an AI model. Look for patterns such as overly polished language, unnatural phrasing, repetitive structures, or lack of personal tone. Consider the context if provided to assess authenticity.';

    public string $responseInstruction = 'Return JSON object with: "ai" (boolean), "confidence" (float 0.00-1.00).';
}
