<?php

namespace Contextr\Checks;

use Contextr\Response\Types\BoolType;

class Ai extends Check
{
    public string $subject = 'ai';

    public string $baseInstruction = 'Determine if this text was likely generated by an AI model. Look for patterns such as overly polished language, unnatural phrasing, repetitive structures, or lack of personal tone. Consider the context if provided to assess authenticity.';

    protected function finishResponseMap(): void
    {
        $this->responseMap = array_merge([new BoolType(name: 'ai', default: false)], $this->responseMap);
    }
}
